[package]
org = "kruutteri1"
name = "java_time_utils"
version = "1.0.4"
readme="docs/Reference.md"
icon="icon.png"
distribution = "2201.13.4"
keywords = ["java-time", "date", "time", "localdate", "localdatetime", "localtime"]
repository = "https://github.com/Kruutteri1/java_time_utils"
license = ["Apache-2.0"]
authors = ["kruutteri1"]

[build-options]
observabilityIncluded = true



